import ExcelJS from "exceljs";
import {
  formatSalesLedgerDate,
  formatSalesLedgerDateTime,
  salesLedgerChannelLabel,
  salesLedgerLocationLabel,
  salesLedgerPeriodLabel,
  salesLedgerReportTitle,
  type SalesLedgerReport
} from "./sales-ledger.service.js";
import { EXCEL_DATE_FORMAT, EXCEL_DATETIME_FORMAT, manilaExcelDate } from "../utils/excel-dates.js";

export type SalesLedgerWorkbookAnalytics = {
  inventoryPlanning: Array<{
    item: string;
    category: string;
    status: string;
    stock: number;
    unitsSold: number;
    stockCoverDays: number | null;
    suggestedReorderQuantity: number;
    recommendation: string;
  }>;
  reconciliation: Array<{
    severity: string;
    label: string;
    referenceCode: string | null;
    eventAt: string;
    amount: number;
    paymentId: string | null;
    receiptId: string | null;
  }>;
};

const EMPTY_WORKBOOK_ANALYTICS: SalesLedgerWorkbookAnalytics = {
  inventoryPlanning: [],
  reconciliation: []
};

const PESO_NUM_FMT = '"\u20b1"#,##0.00';

const WESCOMM_GREEN = "FF006633";
const WESCOMM_SOFT_GREEN = "FFEAF5EC";
const WESCOMM_BORDER = "FFB8D7BF";
const TEXT_COLOR = "FF17211B";
const MUTED_COLOR = "FF5F6D66";
const STRIPE_FILL = "FFF3F8F4";
const VOID_RED = "FFB3261E";
const BODY_FONT = "Aptos";
const BODY_SIZE = 9;
const HEADER_SIZE = 9;

function pesoCell(cell: ExcelJS.Cell, value: number) {
  cell.value = value;
  cell.numFmt = PESO_NUM_FMT;
}

function dateTimeCell(cell: ExcelJS.Cell, value: string) {
  cell.value = manilaExcelDate(value);
  cell.numFmt = EXCEL_DATETIME_FORMAT;
}

function dateCell(cell: ExcelJS.Cell, value: string) {
  cell.value = manilaExcelDate(`${value.slice(0, 10)}T00:00:00+08:00`);
  cell.numFmt = EXCEL_DATE_FORMAT;
}

type CellStyle = Partial<ExcelJS.Style> & {
  fill?: ExcelJS.Fill;
  border?: Partial<ExcelJS.Borders>;
  font?: Partial<ExcelJS.Font>;
};

function applyStyle(cell: ExcelJS.Cell, style: CellStyle) {
  cell.font = { name: BODY_FONT, size: BODY_SIZE, color: { argb: TEXT_COLOR }, ...style.font };
  if (style.fill) cell.fill = style.fill;
  if (style.border) cell.border = style.border;
  if (style.alignment) cell.alignment = style.alignment;
}

function pageSetupForWorksheet(worksheet: ExcelJS.Worksheet, headerRowNumber: number) {
  worksheet.pageSetup = {
    paperSize: 9,
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    printTitlesRow: `${headerRowNumber}:${headerRowNumber}`,
    horizontalCentered: true,
    margins: {
      left: 0.3,
      right: 0.3,
      top: 0.5,
      bottom: 0.5,
      header: 0.25,
      footer: 0.25
    }
  };
  worksheet.headerFooter.oddFooter =
    `&L&"${BODY_FONT},Regular"&8WESCOMM Sales Report&R&"${BODY_FONT},Bold"&8Page &P of &N  |  &D &T`;
  worksheet.headerFooter.oddHeader = `&C&"${BODY_FONT},Bold"&8WESCOMM`;
  worksheet.properties.defaultRowHeight = 14;
}

function setPrintArea(worksheet: ExcelJS.Worksheet, lastRow: number, lastColumn: number) {
  worksheet.pageSetup.printArea = `A1:${worksheet.getColumn(lastColumn).letter}${lastRow}`;
}

const tableBorder = {
  top: { style: "thin" as const, color: { argb: WESCOMM_BORDER } },
  left: { style: "thin" as const, color: { argb: WESCOMM_BORDER } },
  bottom: { style: "thin" as const, color: { argb: WESCOMM_BORDER } },
  right: { style: "thin" as const, color: { argb: WESCOMM_BORDER } }
};

function titleRows(worksheet: ExcelJS.Worksheet, report: SalesLedgerReport, columnCount: number) {
  const mergeAcross = columnCount - 1;
  worksheet.mergeCells(1, 1, 1, columnCount);
  applyStyle(worksheet.getCell(1, 1), {
    font: { name: BODY_FONT, size: 16, bold: true, color: { argb: WESCOMM_GREEN } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(1, 1).value = "WESCOMM";
  worksheet.getRow(1).height = 22;

  worksheet.mergeCells(2, 1, 2, columnCount);
  applyStyle(worksheet.getCell(2, 1), {
    font: { name: BODY_FONT, size: 13, bold: true, color: { argb: TEXT_COLOR } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(2, 1).value = salesLedgerReportTitle(report.range.period);
  worksheet.getRow(2).height = 20;

  worksheet.mergeCells(3, 1, 3, columnCount);
  applyStyle(worksheet.getCell(3, 1), {
    font: { name: BODY_FONT, size: 9, color: { argb: MUTED_COLOR } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(3, 1).value = "Wesleyan University-Philippines \u2014 Integrated Commissary Management System";
  worksheet.getRow(3).height = 14;

  const metadata: Array<[[string, string], [string, string]]> = [
    [["Reporting period", report.range.label], ["Generated", formatSalesLedgerDateTime(report.generatedAt)]],
    [["Generated by", report.generatedBy ?? "Not recorded"], ["Timezone", "Asia/Manila"]],
    [["Channel", salesLedgerChannelLabel(report.filters.channel)], ["Collection location", salesLedgerLocationLabel(report.filters.collectionLocation)]]
  ];
  metadata.forEach((pairs, index) => {
    const rowNumber = 4 + index;
    const placements = [
      { labelStart: 1, labelEnd: 2, valueStart: 3, valueEnd: 6 },
      { labelStart: 7, labelEnd: 8, valueStart: 9, valueEnd: columnCount }
    ];
    pairs.forEach(([label, value], pairIndex) => {
      const placement = placements[pairIndex];
      worksheet.mergeCells(rowNumber, placement.labelStart, rowNumber, placement.labelEnd);
      worksheet.mergeCells(rowNumber, placement.valueStart, rowNumber, placement.valueEnd);
      applyStyle(worksheet.getCell(rowNumber, placement.labelStart), {
        font: { bold: true, size: BODY_SIZE, color: { argb: TEXT_COLOR } },
        fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
        alignment: { vertical: "middle", wrapText: true }
      });
      worksheet.getCell(rowNumber, placement.labelStart).value = label;
      applyStyle(worksheet.getCell(rowNumber, placement.valueStart), {
        alignment: { vertical: "middle", wrapText: true }
      });
      worksheet.getCell(rowNumber, placement.valueStart).value = value;
    });
    worksheet.getRow(rowNumber).height = 18;
  });

  return 3 + metadata.length;
}

function summarySection(worksheet: ExcelJS.Worksheet, report: SalesLedgerReport, startRow: number, columnCount: number) {
  worksheet.mergeCells(startRow, 1, startRow, columnCount);
  applyStyle(worksheet.getCell(startRow, 1), {
    font: { bold: true, size: 10, color: { argb: "FFFFFFFF" } },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_GREEN } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(startRow, 1).value = "Summary";
  worksheet.getRow(startRow).height = 16;

  const summary = report.summary;
  const figureRows: Array<Array<[number, number, string, string, string | null, string?]>> = [
    [
      [1, 2, "Transactions", summary.validSalesTransactions.toLocaleString("en-PH"), null],
      [3, 5, "Units sold", summary.totalUnitsSold.toLocaleString("en-PH"), null],
      [6, 8, "Reservation sales", pesoLabel(summary.reservationSales.amount), transactionCount(summary.reservationSales.count)],
      [9, 11, "Walk-in sales", pesoLabel(summary.walkInSales.amount), transactionCount(summary.walkInSales.count)]
    ],
    [
      [1, 5, "Total recognized sales", pesoLabel(summary.totalRecognizedSales), null, WESCOMM_GREEN],
      [6, 8, "Voids processed", summary.voidsProcessed.count.toLocaleString("en-PH"), "Listed on the Voids sheet"],
      [9, 11, "Void amount", pesoLabel(summary.voidsProcessed.amount), "Excluded from recognized sales", VOID_RED]
    ]
  ];
  figureRows.forEach((figures, rowIndex) => {
    const rowNumber = startRow + 1 + rowIndex;
    figures.forEach(([start, end, label, value, detail, color]) => {
      worksheet.mergeCells(rowNumber, start, rowNumber, end);
      const cell = worksheet.getCell(rowNumber, start);
      cell.value = {
        richText: [
          { text: `${label}\n`, font: { name: BODY_FONT, size: 8, bold: true, color: { argb: MUTED_COLOR } } },
          { text: value, font: { name: BODY_FONT, size: 12, bold: true, color: { argb: color ?? TEXT_COLOR } } },
          ...(detail ? [{ text: `\n${detail}`, font: { name: BODY_FONT, size: 8, color: { argb: MUTED_COLOR } } }] : [])
        ]
      };
      applyStyle(cell, {
        fill: { type: "pattern", pattern: "solid", fgColor: { argb: rowIndex === 1 && start === 1 ? WESCOMM_SOFT_GREEN : "FFFFFFFF" } },
        border: tableBorder,
        alignment: { vertical: "middle", horizontal: "left", indent: 1, wrapText: true }
      });
    });
    worksheet.getRow(rowNumber).height = 44;
  });

  return startRow + 4;
}

function transactionCount(count: number) {
  return `${count.toLocaleString("en-PH")} transaction${count === 1 ? "" : "s"}`;
}

function pesoLabel(amount: number) {
  return `\u20b1${amount.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function headerRow(worksheet: ExcelJS.Worksheet, rowNumber: number, headers: string[], numericColumns: number[] = []) {
  headers.forEach((heading, index) => {
    const cell = worksheet.getCell(rowNumber, index + 1);
    applyStyle(cell, {
      font: { bold: true, size: HEADER_SIZE, color: { argb: "FFFFFFFF" } },
      fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_GREEN } },
      alignment: { vertical: "middle", horizontal: numericColumns.includes(index + 1) ? "right" : "left", wrapText: true },
      border: tableBorder
    });
    cell.value = heading;
  });
  worksheet.getRow(rowNumber).height = 26;
}

function emptyReportNote(worksheet: ExcelJS.Worksheet, rowNumber: number, columnCount: number) {
  worksheet.mergeCells(rowNumber, 1, rowNumber, columnCount);
  applyStyle(worksheet.getCell(rowNumber, 1), {
    font: { italic: true, bold: true, color: { argb: "FF8A5A00" } },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFF4D6" } },
    alignment: { vertical: "middle", horizontal: "center" }
  });
  worksheet.getCell(rowNumber, 1).value = "No valid sales found for this period.";
  worksheet.getRow(rowNumber).height = 24;
}

function signatureBlock(worksheet: ExcelJS.Worksheet, rowNumber: number, columnCount: number) {
  const labels = ["Prepared by:", "Reviewed by:", "Approved by:"];
  const firstColumn = 2;
  const span = Math.floor((columnCount - firstColumn + 1) / labels.length);
  labels.forEach((label, index) => {
    const start = firstColumn + index * span;
    worksheet.mergeCells(rowNumber, start, rowNumber, Math.min(start + span - 1, columnCount));
    const cell = worksheet.getCell(rowNumber, start);
    cell.value = `${label} ______________________`;
    applyStyle(cell, { alignment: { vertical: "middle" } });
  });
  worksheet.getRow(rowNumber).height = 22;
}

export function buildSalesLedgerWorkbook(
  report: SalesLedgerReport,
  analytics: SalesLedgerWorkbookAnalytics = EMPTY_WORKBOOK_ANALYTICS
) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "WESCOMM";
  workbook.company = "Wesleyan University-Philippines";
  workbook.created = new Date(report.generatedAt);
  workbook.modified = new Date(report.generatedAt);

  buildSalesReportSheet(workbook, report);
  buildProductSummarySheet(workbook, report);
  buildVoidedSheet(workbook, report);
  buildInventoryPlanningSheet(workbook, report, analytics.inventoryPlanning);
  buildReconciliationSheet(workbook, report, analytics.reconciliation);

  return workbook;
}

function buildSalesReportSheet(workbook: ExcelJS.Workbook, report: SalesLedgerReport) {
  const worksheet = workbook.addWorksheet("Sales Report");
  worksheet.columns = [
    { width: 6 },
    { width: 23 },
    { width: 15 },
    { width: 12 },
    { width: 24 },
    { width: 15 },
    { width: 44 },
    { width: 7 },
    { width: 13 },
    { width: 18 },
    { width: 14 }
  ];
  const columnCount = worksheet.columns.length;

  const headerRowNumber = summarySection(
    worksheet,
    report,
    titleRows(worksheet, report, columnCount) + 1,
    columnCount
  );
  headerRow(worksheet, headerRowNumber, [
    "#",
    "Date/Time",
    "Receipt No.",
    "Type",
    "Student/Buyer",
    "Order Ref.",
    "Items",
    "Qty",
    "Collection Point",
    "Cashier",
    "Amount"
  ], [1, 8, 11]);

  let currentRow = headerRowNumber + 1;
  if (!report.sales.length) {
    emptyReportNote(worksheet, currentRow, columnCount);
    currentRow += 1;
  } else {
    report.sales.forEach((sale) => {
      const cells = worksheet.getRow(currentRow).getCell(1);
      const rowNumber = currentRow;
      const stripe = rowNumber % 2 === 0;
      const baseStyle: CellStyle = {
        alignment: { vertical: "top", wrapText: true },
        border: { bottom: { style: "thin", color: { argb: "FFE2E9E3" } } },
        ...(stripe ? { fill: { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } } } : {})
      };

      cells.value = sale.sequence;
      applyStyle(cells, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });

      const dateTime = worksheet.getCell(rowNumber, 2);
      dateTimeCell(dateTime, sale.timestamp);
      applyStyle(dateTime, { ...baseStyle, alignment: { vertical: "top", horizontal: "left" } });

      applyStyle(worksheet.getCell(rowNumber, 3), { ...baseStyle, font: { bold: true } });
      worksheet.getCell(rowNumber, 3).value = sale.receiptCode;

      applyStyle(worksheet.getCell(rowNumber, 4), baseStyle);
      worksheet.getCell(rowNumber, 4).value = sale.type === "WALK_IN" ? "Walk-in" : "Reservation";

      applyStyle(worksheet.getCell(rowNumber, 5), baseStyle);
      worksheet.getCell(rowNumber, 5).value = sale.studentNumber
        ? `${sale.studentName} (${sale.studentNumber})`
        : sale.studentName;

      applyStyle(worksheet.getCell(rowNumber, 6), baseStyle);
      worksheet.getCell(rowNumber, 6).value = sale.orderReference ?? "\u2014";

      applyStyle(worksheet.getCell(rowNumber, 7), baseStyle);
      worksheet.getCell(rowNumber, 7).value = sale.itemLines.join("\n");

      applyStyle(worksheet.getCell(rowNumber, 8), { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      worksheet.getCell(rowNumber, 8).value = sale.quantity;
      worksheet.getCell(rowNumber, 8).numFmt = "#,##0";

      applyStyle(worksheet.getCell(rowNumber, 9), baseStyle);
      worksheet.getCell(rowNumber, 9).value = sale.collectionPoint === "TREASURER" ? "Treasury" : "Commissary";

      applyStyle(worksheet.getCell(rowNumber, 10), baseStyle);
      worksheet.getCell(rowNumber, 10).value = sale.cashierName ?? "\u2014";

      const amountCell = worksheet.getCell(rowNumber, 11);
      pesoCell(amountCell, sale.amount);
      applyStyle(amountCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" }, font: { bold: true } });

      worksheet.getRow(rowNumber).height = Math.max(14, 13 * Math.max(1, sale.itemLines.length));
      currentRow += 1;
    });
  }

  const totalRowNumber = currentRow;
  const grandTotalStyle: CellStyle = {
    font: { bold: true, size: 10 },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
    alignment: { vertical: "middle", horizontal: "right" },
    border: tableBorder
  };
  worksheet.mergeCells(totalRowNumber, 1, totalRowNumber, 7);
  applyStyle(worksheet.getCell(totalRowNumber, 1), grandTotalStyle);
  worksheet.getCell(totalRowNumber, 1).value = "Grand Total";
  applyStyle(worksheet.getCell(totalRowNumber, 8), grandTotalStyle);
  worksheet.getCell(totalRowNumber, 8).value = report.summary.totalUnitsSold;
  worksheet.getCell(totalRowNumber, 8).numFmt = "#,##0";
  worksheet.mergeCells(totalRowNumber, 9, totalRowNumber, 10);
  applyStyle(worksheet.getCell(totalRowNumber, 9), grandTotalStyle);
  const totalCell = worksheet.getCell(totalRowNumber, 11);
  pesoCell(totalCell, report.summary.totalRecognizedSales);
  applyStyle(totalCell, {
    font: { bold: true, size: 10, color: { argb: WESCOMM_GREEN } },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
    alignment: { vertical: "middle", horizontal: "right" },
    border: tableBorder
  });
  worksheet.getRow(totalRowNumber).height = 16;

  signatureBlock(worksheet, totalRowNumber + 2, columnCount);

  pageSetupForWorksheet(worksheet, headerRowNumber);
  setPrintArea(worksheet, totalRowNumber + 4, columnCount);
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber, showGridLines: false, zoomScale: 85 }];
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: Math.max(headerRowNumber, totalRowNumber - 1), column: columnCount }
  };
}

function buildProductSummarySheet(workbook: ExcelJS.Workbook, report: SalesLedgerReport) {
  const worksheet = workbook.addWorksheet("Product Summary", {
    views: [{ state: "frozen", ySplit: 4 }]
  });
  worksheet.columns = [
    { width: 30 },
    { width: 18 },
    { width: 26 },
    { width: 13 },
    { width: 14 },
    { width: 14 },
    { width: 14 }
  ];
  const columnCount = worksheet.columns.length;

  worksheet.mergeCells(1, 1, 1, columnCount);
  applyStyle(worksheet.getCell(1, 1), {
    font: { name: BODY_FONT, size: 12, bold: true, color: { argb: WESCOMM_GREEN } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(1, 1).value = `Product Summary \u2014 ${salesLedgerReportTitle(report.range.period)}`;
  worksheet.getRow(1).height = 18;

  worksheet.mergeCells(2, 1, 2, columnCount);
  applyStyle(worksheet.getCell(2, 1), { font: { color: { argb: MUTED_COLOR } } });
  worksheet.getCell(2, 1).value = `${report.range.label} \u2014 ${salesLedgerChannelLabel(report.filters.channel)} \u2014 ${salesLedgerLocationLabel(report.filters.collectionLocation)}`;

  const headerRowNumber = 4;
  headerRow(worksheet, headerRowNumber, ["Item", "Category", "SKU/Option", "Quantity Sold", "Sales", "COGS", "Gross Profit"], [4, 5, 6, 7]);

  let currentRow = headerRowNumber + 1;
  if (!report.productSummary.length) {
    emptyReportNote(worksheet, currentRow, columnCount);
    currentRow += 1;
  } else {
    report.productSummary.forEach((summary) => {
      const rowNumber = currentRow;
      const stripe = rowNumber % 2 === 0;
      const baseStyle: CellStyle = {
        alignment: { vertical: "top", wrapText: true },
        border: { bottom: { style: "thin", color: { argb: "FFE2E9E3" } } },
        ...(stripe ? { fill: { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } } } : {})
      };
      applyStyle(worksheet.getCell(rowNumber, 1), { ...baseStyle, font: { bold: true } });
      worksheet.getCell(rowNumber, 1).value = summary.item;
      applyStyle(worksheet.getCell(rowNumber, 2), baseStyle);
      worksheet.getCell(rowNumber, 2).value = summary.category ?? "\u2014";
      applyStyle(worksheet.getCell(rowNumber, 3), baseStyle);
      worksheet.getCell(rowNumber, 3).value = summary.skuOrOption ?? "\u2014";
      applyStyle(worksheet.getCell(rowNumber, 4), { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      worksheet.getCell(rowNumber, 4).value = summary.quantity;
      worksheet.getCell(rowNumber, 4).numFmt = "#,##0";
      const salesCell = worksheet.getCell(rowNumber, 5);
      pesoCell(salesCell, summary.sales);
      applyStyle(salesCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      const cogsCell = worksheet.getCell(rowNumber, 6);
      pesoCell(cogsCell, summary.cogs);
      applyStyle(cogsCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      const profitCell = worksheet.getCell(rowNumber, 7);
      pesoCell(profitCell, summary.grossProfit);
      applyStyle(profitCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" }, font: { bold: true, color: { argb: WESCOMM_GREEN } } });
      currentRow += 1;
    });
  }

  const lastDataRow = Math.max(headerRowNumber, currentRow - 1);
  const totalRowNumber = currentRow;
  const totals = report.productSummary.reduce(
    (sum, row) => ({ quantity: sum.quantity + row.quantity, sales: sum.sales + row.sales, cogs: sum.cogs + row.cogs, grossProfit: sum.grossProfit + row.grossProfit }),
    { quantity: 0, sales: 0, cogs: 0, grossProfit: 0 }
  );
  const totalStyle: CellStyle = {
    font: { bold: true, size: 10 },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
    alignment: { vertical: "middle", horizontal: "right" },
    border: tableBorder
  };
  worksheet.mergeCells(totalRowNumber, 1, totalRowNumber, 3);
  applyStyle(worksheet.getCell(totalRowNumber, 1), totalStyle);
  worksheet.getCell(totalRowNumber, 1).value = "Total";
  applyStyle(worksheet.getCell(totalRowNumber, 4), totalStyle);
  worksheet.getCell(totalRowNumber, 4).value = totals.quantity;
  worksheet.getCell(totalRowNumber, 4).numFmt = "#,##0";
  ([[5, totals.sales], [6, totals.cogs], [7, totals.grossProfit]] as const).forEach(([column, value]) => {
    const cell = worksheet.getCell(totalRowNumber, column);
    pesoCell(cell, value);
    applyStyle(cell, column === 7 ? { ...totalStyle, font: { bold: true, size: 10, color: { argb: WESCOMM_GREEN } } } : totalStyle);
  });
  worksheet.getRow(totalRowNumber).height = 16;

  pageSetupForWorksheet(worksheet, headerRowNumber);
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber, showGridLines: false, zoomScale: 90 }];
  setPrintArea(worksheet, totalRowNumber, columnCount);
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: lastDataRow, column: columnCount }
  };
}

function buildVoidedSheet(workbook: ExcelJS.Workbook, report: SalesLedgerReport) {
  const worksheet = workbook.addWorksheet("Voids", {
    views: [{ state: "frozen", ySplit: 4 }]
  });
  worksheet.columns = [
    { width: 16 },
    { width: 23 },
    { width: 23 },
    { width: 12 },
    { width: 14 },
    { width: 30 },
    { width: 18 },
    { width: 18 }
  ];
  const columnCount = worksheet.columns.length;

  worksheet.mergeCells(1, 1, 1, columnCount);
  applyStyle(worksheet.getCell(1, 1), {
    font: { name: BODY_FONT, size: 12, bold: true, color: { argb: VOID_RED } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(1, 1).value = `Voids \u2014 ${salesLedgerReportTitle(report.range.period)}`;
  worksheet.getRow(1).height = 18;

  worksheet.mergeCells(2, 1, 2, columnCount);
  applyStyle(worksheet.getCell(2, 1), { font: { color: { argb: MUTED_COLOR } } });
  worksheet.getCell(2, 1).value = `${report.range.label} \u2014 voids processed during the selected period, excluded from valid sales.`;

  const headerRowNumber = 4;
  headerRow(worksheet, headerRowNumber, ["Receipt", "Original Sale Date", "Void Date", "Type", "Amount", "Reason", "Cashier", "Voided By"], [5]);

  let currentRow = headerRowNumber + 1;
  if (!report.voids.length) {
    emptyReportNote(worksheet, currentRow, columnCount);
    currentRow += 1;
  } else {
    report.voids.forEach((voidRow) => {
      const rowNumber = currentRow;
      const stripe = rowNumber % 2 === 0;
      const baseStyle: CellStyle = {
        alignment: { vertical: "top", wrapText: true },
        border: { bottom: { style: "thin", color: { argb: "FFE2E9E3" } } },
        ...(stripe ? { fill: { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } } } : {})
      };
      applyStyle(worksheet.getCell(rowNumber, 1), { ...baseStyle, font: { bold: true } });
      worksheet.getCell(rowNumber, 1).value = voidRow.receiptCode;
      const originalDate = worksheet.getCell(rowNumber, 2);
      if (voidRow.originalSaleAt) dateTimeCell(originalDate, voidRow.originalSaleAt);
      else originalDate.value = "\u2014";
      applyStyle(originalDate, { ...baseStyle, alignment: { vertical: "top", horizontal: "left" } });
      const voidDate = worksheet.getCell(rowNumber, 3);
      dateTimeCell(voidDate, voidRow.voidedAt);
      applyStyle(voidDate, { ...baseStyle, alignment: { vertical: "top", horizontal: "left" } });
      applyStyle(worksheet.getCell(rowNumber, 4), baseStyle);
      worksheet.getCell(rowNumber, 4).value = voidRow.type === "WALK_IN" ? "Walk-in" : "Reservation";
      const amountCell = worksheet.getCell(rowNumber, 5);
      pesoCell(amountCell, voidRow.amount);
      applyStyle(amountCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      applyStyle(worksheet.getCell(rowNumber, 6), baseStyle);
      worksheet.getCell(rowNumber, 6).value = voidRow.reason ?? "\u2014";
      applyStyle(worksheet.getCell(rowNumber, 7), baseStyle);
      worksheet.getCell(rowNumber, 7).value = voidRow.cashierName ?? "\u2014";
      applyStyle(worksheet.getCell(rowNumber, 8), baseStyle);
      worksheet.getCell(rowNumber, 8).value = voidRow.voidedBy ?? "\u2014";
      currentRow += 1;
    });
  }

  const totalRowNumber = currentRow;
  worksheet.mergeCells(totalRowNumber, 1, totalRowNumber, 4);
  applyStyle(worksheet.getCell(totalRowNumber, 1), {
    font: { bold: true },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
    alignment: { vertical: "middle", horizontal: "right" },
    border: tableBorder
  });
  worksheet.getCell(totalRowNumber, 1).value = "Total void amount (not part of recognized sales)";
  const totalCell = worksheet.getCell(totalRowNumber, 5);
  pesoCell(totalCell, report.summary.voidsProcessed.amount);
  applyStyle(totalCell, {
    font: { bold: true, color: { argb: VOID_RED } },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: WESCOMM_SOFT_GREEN } },
    alignment: { vertical: "middle", horizontal: "right" },
    border: tableBorder
  });
  worksheet.getRow(totalRowNumber).height = 16;

  pageSetupForWorksheet(worksheet, headerRowNumber);
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber, showGridLines: false, zoomScale: 90 }];
  setPrintArea(worksheet, totalRowNumber, columnCount);
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: Math.max(headerRowNumber, totalRowNumber - 1), column: columnCount }
  };
}

function buildInventoryPlanningSheet(
  workbook: ExcelJS.Workbook,
  report: SalesLedgerReport,
  rows: SalesLedgerWorkbookAnalytics["inventoryPlanning"]
) {
  const worksheet = workbook.addWorksheet("Inventory Planning", {
    views: [{ state: "frozen", ySplit: 4 }]
  });
  worksheet.columns = [
    { width: 30 },
    { width: 18 },
    { width: 12 },
    { width: 12 },
    { width: 11 },
    { width: 12 },
    { width: 16 },
    { width: 44 }
  ];
  const columnCount = worksheet.columns.length;

  worksheet.mergeCells(1, 1, 1, columnCount);
  applyStyle(worksheet.getCell(1, 1), {
    font: { name: BODY_FONT, size: 12, bold: true, color: { argb: WESCOMM_GREEN } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(1, 1).value = `Inventory Planning \u2014 ${salesLedgerReportTitle(report.range.period)}`;
  worksheet.getRow(1).height = 18;

  worksheet.mergeCells(2, 1, 2, columnCount);
  applyStyle(worksheet.getCell(2, 1), { font: { color: { argb: MUTED_COLOR } } });
  worksheet.getCell(2, 1).value = `${report.range.label} \u2014 current stock and reorder suggestions for the selected period.`;

  const headerRowNumber = 4;
  headerRow(worksheet, headerRowNumber, ["Item", "Category", "Status", "Current Stock", "Units Sold", "Stock Cover", "Suggested Reorder", "Recommendation"], [4, 5, 7]);

  let currentRow = headerRowNumber + 1;
  if (!rows.length) {
    emptyReportNote(worksheet, currentRow, columnCount);
    currentRow += 1;
  } else {
    rows.forEach((row) => {
      const rowNumber = currentRow;
      const stripe = rowNumber % 2 === 0;
      const baseStyle: CellStyle = {
        alignment: { vertical: "top", wrapText: true },
        border: { bottom: { style: "thin", color: { argb: "FFE2E9E3" } } },
        ...(stripe ? { fill: { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } } } : {})
      };
      applyStyle(worksheet.getCell(rowNumber, 1), { ...baseStyle, font: { bold: true } });
      worksheet.getCell(rowNumber, 1).value = row.item;
      applyStyle(worksheet.getCell(rowNumber, 2), baseStyle);
      worksheet.getCell(rowNumber, 2).value = row.category;
      applyStyle(worksheet.getCell(rowNumber, 3), baseStyle);
      worksheet.getCell(rowNumber, 3).value = row.status;
      applyStyle(worksheet.getCell(rowNumber, 4), { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      worksheet.getCell(rowNumber, 4).value = row.stock;
      worksheet.getCell(rowNumber, 4).numFmt = "#,##0";
      applyStyle(worksheet.getCell(rowNumber, 5), { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      worksheet.getCell(rowNumber, 5).value = row.unitsSold;
      worksheet.getCell(rowNumber, 5).numFmt = "#,##0";
      applyStyle(worksheet.getCell(rowNumber, 6), baseStyle);
      worksheet.getCell(rowNumber, 6).value = row.stockCoverDays === null ? "No demand yet" : `${row.stockCoverDays} days`;
      applyStyle(worksheet.getCell(rowNumber, 7), { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      worksheet.getCell(rowNumber, 7).value = row.suggestedReorderQuantity;
      worksheet.getCell(rowNumber, 7).numFmt = "#,##0";
      applyStyle(worksheet.getCell(rowNumber, 8), baseStyle);
      worksheet.getCell(rowNumber, 8).value = row.recommendation;
      currentRow += 1;
    });
  }

  const lastDataRow = Math.max(headerRowNumber, currentRow - 1);
  pageSetupForWorksheet(worksheet, headerRowNumber);
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber, showGridLines: false, zoomScale: 90 }];
  setPrintArea(worksheet, lastDataRow, columnCount);
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: lastDataRow, column: columnCount }
  };
}

function buildReconciliationSheet(
  workbook: ExcelJS.Workbook,
  report: SalesLedgerReport,
  rows: SalesLedgerWorkbookAnalytics["reconciliation"]
) {
  const worksheet = workbook.addWorksheet("Reconciliation", {
    views: [{ state: "frozen", ySplit: 4 }]
  });
  worksheet.columns = [
    { width: 12 },
    { width: 40 },
    { width: 16 },
    { width: 23 },
    { width: 14 },
    { width: 38 },
    { width: 38 }
  ];
  const columnCount = worksheet.columns.length;

  worksheet.mergeCells(1, 1, 1, columnCount);
  applyStyle(worksheet.getCell(1, 1), {
    font: { name: BODY_FONT, size: 12, bold: true, color: { argb: WESCOMM_GREEN } },
    alignment: { vertical: "middle" }
  });
  worksheet.getCell(1, 1).value = `Reconciliation \u2014 ${salesLedgerReportTitle(report.range.period)}`;
  worksheet.getRow(1).height = 18;

  worksheet.mergeCells(2, 1, 2, columnCount);
  applyStyle(worksheet.getCell(2, 1), { font: { color: { argb: MUTED_COLOR } } });
  worksheet.getCell(2, 1).value = `${report.range.label} \u2014 missing receipt and payment issues only.`;

  const headerRowNumber = 4;
  headerRow(worksheet, headerRowNumber, ["Priority", "Issue", "Reservation", "Date", "Amount", "Payment ID", "Receipt ID"], [5]);

  let currentRow = headerRowNumber + 1;
  if (!rows.length) {
    worksheet.mergeCells(currentRow, 1, currentRow, columnCount);
    applyStyle(worksheet.getCell(currentRow, 1), {
      font: { bold: true, color: { argb: WESCOMM_GREEN } },
      alignment: { vertical: "middle", horizontal: "center" }
    });
    worksheet.getCell(currentRow, 1).value = "No reconciliation issues";
    worksheet.getRow(currentRow).height = 18;
    currentRow += 1;
  } else {
    rows.forEach((row) => {
      const rowNumber = currentRow;
      const stripe = rowNumber % 2 === 0;
      const baseStyle: CellStyle = {
        alignment: { vertical: "top", wrapText: true },
        border: { bottom: { style: "thin", color: { argb: "FFE2E9E3" } } },
        ...(stripe ? { fill: { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } } } : {})
      };
      applyStyle(worksheet.getCell(rowNumber, 1), { ...baseStyle, font: { bold: true } });
      worksheet.getCell(rowNumber, 1).value = row.severity;
      applyStyle(worksheet.getCell(rowNumber, 2), baseStyle);
      worksheet.getCell(rowNumber, 2).value = row.label;
      applyStyle(worksheet.getCell(rowNumber, 3), baseStyle);
      worksheet.getCell(rowNumber, 3).value = row.referenceCode ?? "\u2014";
      const dateTime = worksheet.getCell(rowNumber, 4);
      dateTimeCell(dateTime, row.eventAt);
      applyStyle(dateTime, { ...baseStyle, alignment: { vertical: "top", horizontal: "left" } });
      const amountCell = worksheet.getCell(rowNumber, 5);
      pesoCell(amountCell, row.amount);
      applyStyle(amountCell, { ...baseStyle, alignment: { vertical: "top", horizontal: "right" } });
      applyStyle(worksheet.getCell(rowNumber, 6), baseStyle);
      worksheet.getCell(rowNumber, 6).value = row.paymentId ?? "\u2014";
      applyStyle(worksheet.getCell(rowNumber, 7), baseStyle);
      worksheet.getCell(rowNumber, 7).value = row.receiptId ?? "\u2014";
      currentRow += 1;
    });
  }

  const lastDataRow = Math.max(headerRowNumber, currentRow - 1);
  pageSetupForWorksheet(worksheet, headerRowNumber);
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber, showGridLines: false, zoomScale: 90 }];
  setPrintArea(worksheet, lastDataRow, columnCount);
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: lastDataRow, column: columnCount }
  };
}

export function salesLedgerFileName(report: SalesLedgerReport) {
  return `wescomm-sales-report-${report.range.period.toLowerCase()}-${report.range.anchor}.xlsx`;
}

export function salesLedgerFileLabel(report: SalesLedgerReport) {
  return `WESCOMM ${salesLedgerPeriodLabel(report.range.period)} Sales Report (${report.range.label}, ${formatSalesLedgerDate(report.generatedAt)})`;
}
