import { Router } from "express";
import { auditLogsRoutes } from "./audit-logs.routes.js";
import { authRoutes } from "./auth.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { faqsRoutes } from "./faqs.routes.js";
import { globalSearchRoutes } from "./global-search.routes.js";
import { healthRoutes } from "./health.routes.js";
import { inventoryRoutes } from "./inventory.routes.js";
import { messagesRoutes } from "./messages.routes.js";
import { notificationsRoutes } from "./notifications.routes.js";
import { paymentsRoutes } from "./payments.routes.js";
import { pickupRoutes } from "./pickup.routes.js";
import { productsRoutes } from "./products.routes.js";
import { pushRoutes } from "./push.routes.js";
import { realtimeRoutes } from "./realtime.routes.js";
import { receiptsRoutes } from "./receipts.routes.js";
import { reportsRoutes } from "./reports.routes.js";
import { reservationsRoutes } from "./reservations.routes.js";
import { restrictionsRoutes } from "./restrictions.routes.js";
import { staffProductsRoutes } from "./staff-products.routes.js";
import { staffRestrictionsRoutes } from "./staff-restrictions.routes.js";
import { staffStudentsRoutes } from "./staff-students.routes.js";
import { staffUsersRoutes } from "./staff-users.routes.js";
import { uploadsRoutes } from "./uploads.routes.js";
import { usersRoutes } from "./users.routes.js";
import { wishlistRoutes } from "./wishlist.routes.js";
import { wesbotUsageRoutes } from "./wesbot-usage.routes.js";

export const apiRoutes = Router();

apiRoutes.use("/health", healthRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/products", productsRoutes);
apiRoutes.use("/wishlist", wishlistRoutes);
apiRoutes.use("/reservations", reservationsRoutes);
apiRoutes.use("/restrictions", restrictionsRoutes);
apiRoutes.use("/receipts", receiptsRoutes);
apiRoutes.use("/notifications", notificationsRoutes);
apiRoutes.use("/payments", paymentsRoutes);
apiRoutes.use("/pickup", pickupRoutes);
apiRoutes.use("/push", pushRoutes);
apiRoutes.use("/realtime", realtimeRoutes);
apiRoutes.use("/conversations", messagesRoutes);
apiRoutes.use("/messages", messagesRoutes);
apiRoutes.use("/faqs", faqsRoutes);
apiRoutes.use("/staff/products", staffProductsRoutes);
apiRoutes.use("/staff/restrictions", staffRestrictionsRoutes);
apiRoutes.use("/staff/students", staffStudentsRoutes);
apiRoutes.use("/staff/users", staffUsersRoutes);
apiRoutes.use("/staff/uploads", uploadsRoutes);
apiRoutes.use("/staff/inventory", inventoryRoutes);
apiRoutes.use("/staff/search", globalSearchRoutes);
apiRoutes.use("/staff/dashboard", dashboardRoutes);
apiRoutes.use("/staff/reports", reportsRoutes);
apiRoutes.use("/admin/reports", reportsRoutes);
apiRoutes.use("/admin/search", globalSearchRoutes);
apiRoutes.use("/admin/dashboard", dashboardRoutes);
apiRoutes.use("/admin/users", usersRoutes);
apiRoutes.use("/admin/audit-logs", auditLogsRoutes);
apiRoutes.use("/admin/wesbot", wesbotUsageRoutes);
